name: Flutter CI
on:
  workflow_dispatch: 
    inputs:
      REPO:
        description: "URL to repository(You can add branch support by -b branchname after the URL)"
        required: true
      REPO_NAME:
        description: "The name of your repository(must match URL)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone Repo
      run: |
        git clone ${{ github.event.inputs.REPO }}
        cd ${{ github.event.inputs.REPO_NAME }}

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
       # flutter-version-file: ${{ github.event.inputs.REPO_NAME }}/pubspec.yaml # path to pubspec.yaml
    
    - name: Initialize repo
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      id: pwd

    - name: Check Flutter
      run: |
        flutter --version

        cd ${{ github.event.inputs.REPO_NAME }}

        echo "Getting flutter deps"
        flutter pub get

        echo "Checking flutter project"
        # flutter format --set-exit-if-changed .
        flutter analyze .

        echo "Running tests"
        flutter test
      continue-on-error: true

    - name: Build with Flutter
      run: |
        cd ${{ github.event.inputs.REPO_NAME }}

        echo "Starting Build"
        flutter build apk

    - name: Upload to Release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: " ${{ github.event.inputs.REPO_NAME }}/app/build/outputs/apk/*/*.apk"
        default_release_name: ${{ github.event.inputs.REPO_NAME }} ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
