name: Android CI
on:
  workflow_dispatch: 
    inputs:
      REPO:
        description: "URL to repository(You can add branch support by -b branchname after the URL)"
        required: true
      REPO_NAME:
        description: "The name of your repository(must match URL)"
        required: true
      GRADLE_VERSION:
        description: "Override Gradle version to use"
        required: false
      EXTRA:
        description: "Commands to Run before Building"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone Repo
      run: |
        git clone ${{ github.event.inputs.REPO }} --depth=1
        cd ${{ github.event.inputs.REPO_NAME }}

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Initialize repo
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      id: pwd

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      run: |
        cd ${{ github.event.inputs.REPO_NAME }}
        ${{ github.event.inputs.EXTRA }}
          if [ -n "${{ github.event.inputs.GRADLE_VERSION }}" ]; then
              gradle wrapper --gradle-version ${{ github.event.inputs.GRADLE_VERSION }}
              ./gradlew --no-daemon build
          elif [ -f "./gradlew" ]; then
              ./gradlew --no-daemon build
          else
              gradle --no-daemon build
          fi

    - name: Upload to Release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: " ${{ github.event.inputs.REPO_NAME }}/app/build/outputs/apk/*/*.apk"
        default_release_name: ${{ github.event.inputs.REPO_NAME }} ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
